[package]
name = "gbc-input-display"
version = "1.0.0"
authors = ["stringflow"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"